{
 "title": "Directions Service",
 "tags": [
  "Microservices",
  "directions"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_started{job=\"directions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_failed{job=\"directions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"directions\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"directions\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"directions\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_sent{job=\"directions\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received{job=\"directions\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Generate Directions - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_generatedirections_handled_count{job=\"directions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generate Directions - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_generatedirections_guard_bucket{job=\"directions\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Generate Directions - Obtain Directions Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_generatedirections_directions_bucket{job=\"directions\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Generate Directions - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_generatedirections_publish_bucket{job=\"directions\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Directions - Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_getdirections_handled_count{job=\"directions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Directions - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_getdirections_guard_bucket{job=\"directions\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Directions - External Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "directions_application_getdirections_external_bucket{job=\"directions\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}