{
 "title": "Email Service",
 "tags": [
  "Microservices",
  "email"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_started{job=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_failed{job=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"email\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"email\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"email\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_sent{job=\"email\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received{job=\"email\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Send Email Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_sendemail_handled_count{job=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send Email Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_sendemail_guard_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Send Email Obtain Image Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_sendemail_image_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Send Email HTML Generation Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_sendemail_generate_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Send Email Sending Email Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_sendemail_email_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Emails Between Times Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_getemailssentbetweentimes_handled_count{job=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Emails Between Times Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_getemailssentbetweentimes_guard_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Emails Between Times Load Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_getemailssentbetweentimes_load_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Emails To Recipient Times Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_getemailssenttorecipient_handled_count{job=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Emails Sent To Recipient Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_getemailssenttorecipient_guard_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Emails To Recipient Load Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_application_getemailssenttorecipient_load_bucket{job=\"email\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}