{
 "title": "Geocoding Service",
 "tags": [
  "Microservices",
  "geocoding"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_started{job=\"geocoding\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_failed{job=\"geocoding\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"geocoding\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"geocoding\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"geocoding\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_sent{job=\"geocoding\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received{job=\"geocoding\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Geocode Addresses - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_geocodeaddresses_handled_count{job=\"geocoding\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geocode Addresses - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_geocodeaddresses_guard_bucket{job=\"geocoding\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Geocode Addresses - Geocoding Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_geocodeaddresses_geocode_bucket{job=\"geocoding\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Geocode Addresses - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_geocodeaddresses_publish_bucket{job=\"geocoding\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Address Coordinates - Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_getaddresscoordinates_handled_count{job=\"geocoding\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Address Coordinates - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_getaddresscoordinates_guard_bucket{job=\"geocoding\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Address Coordinates - External Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geocoding_application_getaddresscoordinates_external_bucket{job=\"geocoding\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}