{
 "title": "Imaging Service",
 "tags": [
  "Microservices",
  "imaging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# Imaging\n\nThe service to provide an image of the destination."
   },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"public-api\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"imaging\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_threads{job=\"imaging\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{job=\"imaging\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Save Image - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_saveimagecommand_handled_count_total{job=\"imaging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Save Image - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_saveimagecommand_guard_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Save Image - Obtain URL Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_saveimagecommand_imaging_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Save Image - Download Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_saveimagecommand_download_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Save Image - Upload Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_saveimagecommand_upload_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Save Image - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_saveimagecommand_publish_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Image - URL Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_getimageurlquery_handled_count_total{job=\"imaging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Image URL - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_getimageurlquery_guard_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Image - URL External Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imaging_api_getimageurlquery_external_milliseconds_bucket{job=\"imaging\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}