{
 "title": "Public API",
 "tags": [
  "Microservices",
  "publicapi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# Public API\n\nThe initial API to create jobs and request job status."
   },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"public-api\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"public-api\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_threads{job=\"public-api\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{job=\"public-api\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Create Job - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_createjobcommand_handled_count_total{job=\"public-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Job - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_createjobcommand_guard_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create Job - Idempotency Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_createjobcommand_idempotency_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create Job - Save Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_createjobcommand_save_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create Job - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_createjobcommand_publish_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Job Status - Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_getjobstatusquery_handled_count_total{job=\"public-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Job Status - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_getjobstatusquery_guard_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Job Status - Cache Get Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_getjobstatusquery_cache_get_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Job Status - Load Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_getjobstatusquery_load_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Job Status - Cache Set Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_getjobstatusquery_cache_set_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Status - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_updatestatuscommand_handled_count_total{job=\"public-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Status - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_updatestatuscommand_guard_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Status - Update Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "publicapi_api_updatestatuscommand_update_milliseconds_bucket{job=\"public-api\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}