{
 "title": "State Service",
 "tags": [
  "Microservices",
  "state"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_started{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_failed{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"state\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"state\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"state\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_sent{job=\"state\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received{job=\"state\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Create Job - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_createjob_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Job - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_createjob_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create Job - Save Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_createjob_save_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create Job - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_createjob_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Geocoding - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updategeocodingresult_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Geocoding - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updategeocodingresult_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Geocoding - Update Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updategeocodingresult_update_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Geocoding - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updategeocodingresult_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Directions - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updatedirectionsresult_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Directions - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updatedirectionsresult_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Directions - Update Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updatedirectionsresult_update_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Directions - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updatedirectionsresult_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Weather - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateweatherresult_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Weather - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateweatherresult_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Weather - Update Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateweatherresult_update_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Weather - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateweatherresult_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Imaging - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateimagingresult_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Imaging - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateimagingresult_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Imaging - Update Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateimagingresult_update_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Update Imaging - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_updateimagingresult_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notify Job Status - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_notifyjobstatusupdate_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify Job Status - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_notifyjobstatusupdate_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notify Job Status - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_notifyjobstatusupdate_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notify Processing Complete - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_notifyprocessingcomplete_handled_count{job=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify Processing Complete - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_notifyprocessingcomplete_guard_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notify Processing Complete - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_application_notifyprocessingcomplete_publish_bucket{job=\"state\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}