{
 "title": "Weather Service",
 "tags": [
  "Microservices",
  "weather"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_started{job=\"weather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_net_http_requests_failed{job=\"weather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"weather\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"weather\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"weather\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_sent{job=\"weather\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network MB Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received{job=\"weather\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Generate Weather - Commands",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_generateweather_handled_count{job=\"weather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generate Weather - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_generateweather_guard_bucket{job=\"weather\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Generate Weather - Weather Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_generateweather_weather_bucket{job=\"weather\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Generate Weather - Publish Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_generateweather_publish_bucket{job=\"weather\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Weather - Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_getweather_handled_count{job=\"weather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Weather - Guard Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_getweather_guard_bucket{job=\"weather\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Weather - External Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_application_getweather_external_bucket{job=\"weather\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}