apiVersion: 1

datasources:
  - name: Microservices
    uid: DS_PROMETHEUS
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
