@HostAddress = http://localhost:10083

GET {{HostAddress}}/health/status
Accept: application/json

###
GET {{HostAddress}}/health/version
Accept: application/json

###
GET {{HostAddress}}/secrets/vaults
Accept: application/json

###
GET {{HostAddress}}/secrets/vaults/infrastructure
Accept: application/json

###
GET {{HostAddress}}/secrets/vaults/infrastructure/rabbit.vhost
Accept: application/json

###
POST {{HostAddress}}/secrets/vaults/test/test.value
Content-Type: text/plain

Hello World

###
POST {{HostAddress}}/secrets/vaults/test/test.value
Content-Type: application/json

"Hello World"

###
GET {{HostAddress}}/secrets/vaults/test/test.value
Accept: application/json

###
