global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['rabbitmq1:15692', 'rabbitmq2:15692']
  - job_name: 'redis'
    static_configs:
    - targets: ['redis-metrics:9121']
  - job_name: 'public-api'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['publicapi:8081']
  - job_name: 'state'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['state:8081']
  - job_name: 'geocoding'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['geocoding:8081']
  - job_name: 'directions'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['directions:8081']
  - job_name: 'weather'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['weather:8081']
  - job_name: 'imaging'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['imaging:8081']
  - job_name: 'email'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['email:8081']
