# To run from the command line, use the --build option to build the api image
# The command should be run from the folder containing this file
#
# docker compose -p microservices-imaging up -d --build

networks:
  microservices-infrastructure_microservices-net:
    external: true

services:

  api.microservices-imaging:
    image: ${DOCKER_REGISTRY-}api.microservices-imaging
    container_name: api.microservices-imaging
    build:
      context: ../../
      dockerfile: Imaging/Imaging/Imaging.Api/Dockerfile
      target: final
    env_file:
      - docker-compose.env
    restart: no
    extra_hosts:
      - rabbitmq1:172.30.0.2
      - rabbitmq2:172.30.0.3
      - seq:172.30.0.4
      - cloudfiles:172.30.0.8
      - secretsmanager:172.30.0.12
      - telemetry:172.30.0.15
    networks:
      microservices-infrastructure_microservices-net:
        ipv4_address: 172.30.0.70
    ports:
      - 16080:8080 # HTTP
      - 16081:8081 # Prometheus metrics
